spring:
  application:
    name: IMWeb
  redis:
    database: 0
    url: redis://@192.168.235.128:6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
        min-idle: 0
      shutdown-timeout: 100ms
    ssl: false
    timeout: 1000ms
server:
  port: 8080







