spring:
  application:
    name: IMWeb
  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zqq
    password: qwer123!@#
    url: jdbc:mysql://rm-bp1sxm1dwq4wl0b1nuo.mysql.rds.aliyuncs.com/web-db?useUnicode=true&characterEncoding=utf-8

server:
  port: 8080








mybatis:
  type-aliases-package: com.bestbeat.web.model

